<a href="https://colab.research.google.com/github/dragonSwords98/deeppicar/blob/main/Export_To_Tflite_UInt8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Mount Google Drive
from google.colab import drive
drive.mount('/content/gdrive')
model_dir = '/content/gdrive/My Drive/Colab Notebooks/'
#!rm -rf '{model_dir}'
#os.makedirs(model_dir, exist_ok=True)
!ls -ltra '{model_dir}'/deeppicar

Mounted at /content/gdrive
total 23721
drwx------ 2 root root     4096 Nov 28 19:54 images
drwx------ 2 root root     4096 Dec  9 04:18 object_detection
-rw------- 1 root root 24281515 Dec 20 19:37 tensorflow_traffic_sign_detection.ipynb


In [2]:
import os
# If you forked the repository, you can replace the link.
repo_url = 'https://github.com/dctian/DeepPiCar'

%cd /content

repo_dir_path = os.path.abspath(os.path.join('.', os.path.basename(repo_url)))

!git clone {repo_url}
%cd {repo_dir_path}

print('Pull it so that we have the latest code/data')
!git pull

/content
Cloning into 'DeepPiCar'...
remote: Enumerating objects: 1027, done.
remote: Total 1027 (delta 0), reused 0 (delta 0), pack-reused 1027
Receiving objects: 100% (1027/1027), 141.14 MiB | 36.95 MiB/s, done.
Resolving deltas: 100% (320/320), done.
/content/DeepPiCar
Pull it so that we have the latest code/data
Already up to date.


In [3]:
%cd /content/
!git clone --q https://github.com/tensorflow/models.git

/content


In [4]:
!apt-get install -qq protobuf-compiler python-pil python-lxml python-tk
!pip install -qq Cython contextlib2 pillow lxml matplotlib
!pip install -qq pycocotools

%cd /content/models/research/
!protoc object_detection/protos/*.proto --python_out=.

Selecting previously unselected package python-bs4.
(Reading database ... 145480 files and directories currently installed.)
Preparing to unpack .../0-python-bs4_4.6.0-1_all.deb ...
Unpacking python-bs4 (4.6.0-1) ...
Selecting previously unselected package python-pkg-resources.
Preparing to unpack .../1-python-pkg-resources_39.0.1-2_all.deb ...
Unpacking python-pkg-resources (39.0.1-2) ...
Selecting previously unselected package python-chardet.
Preparing to unpack .../2-python-chardet_3.0.4-1_all.deb ...
Unpacking python-chardet (3.0.4-1) ...
Selecting previously unselected package python-six.
Preparing to unpack .../3-python-six_1.11.0-2_all.deb ...
Unpacking python-six (1.11.0-2) ...
Selecting previously unselected package python-webencodings.
Preparing to unpack .../4-python-webencodings_0.5-2_all.deb ...
Unpacking python-webencodings (0.5-2) ...
Selecting previously unselected package python-html5lib.
Preparing to unpack .../5-python-html5lib_0.999999999-1_all.deb ...
Unpacking pyt

In [5]:
%cp object_detection/packages/tf2/setup.py .
!python -m pip install .
!python object_detection/builders/model_builder_tf2_test.py

Processing /content/models/research
     |████████████████████████████████| 8.9MB 4.6MB/s 
     |████████████████████████████████| 358kB 41.3MB/s 
     |████████████████████████████████| 849kB 45.5MB/s 
     |████████████████████████████████| 829kB 45.2MB/s 
     |████████████████████████████████| 61kB 8.1MB/s 
     |████████████████████████████████| 2.0MB 49.7MB/s 
     |████████████████████████████████| 63.8MB 79kB/s 
     |████████████████████████████████| 51kB 6.6MB/s 
     |████████████████████████████████| 153kB 47.8MB/s 
     |████████████████████████████████| 61kB 7.2MB/s 
     |████████████████████████████████| 174kB 37.5MB/s 
     |████████████████████████████████| 36.7MB 91kB/s 
     |████████████████████████████████| 102kB 11.8MB/s 
     |████████████████████████████████| 1.1MB 40.1MB/s 
     |████████████████████████████████| 112kB 48.0MB/s 
  Created wheel for object-detection: filename=object_detection-0.1-cp36-none-any.whl size=1606870 sha256=3a83c44b212824af009b0e1811d

In [ ]:
!python /content/models/research/object_detection/export_tflite_graph_tf2.py \
    --pipeline_config_path "/content/gdrive/MyDrive/Colab Notebooks/pre-trained-models/ssd_mobilenet_v2_fpnlite_320x320_coco17_tpu-8/pipeline.config" \
    --trained_checkpoint_dir "/content/gdrive/MyDrive/Colab Notebooks"\
    --output_directory "/content/gdrive/MyDrive/Colab Notebooks/export-tflite"

2020-12-21 01:02:14.707953: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
2020-12-21 01:02:17.688479: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2020-12-21 01:02:17.689507: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcuda.so.1
2020-12-21 01:02:17.699630: E tensorflow/stream_executor/cuda/cuda_driver.cc:328] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2020-12-21 01:02:17.699698: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (1b677d6651a5): /proc/driver/nvidia/version does not exist
2020-12-21 01:02:17.700297: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
2020-12-21 01:02:27.900367: I tensorflow/compiler/jit/xla_gpu_device.cc:99] 

load the tflite from fine_tuned_model/model.tflite


In [2]:
!pip install tf-nightly-gpu


In [3]:
import tensorflow as tf
tf.__version__
# converter = tf.lite.TFLiteConverter.from_saved_model('/content/gdrive/MyDrive/Colab Notebooks/export-tflite/saved_model')
# tflite_model = converter.convert()

# with open('/content/gdrive/MyDrive/Colab Notebooks/export-tflite/model.tflite', 'wb') as f:
#   f.write(tflite_model)

'2.5.0-dev20201224'

In [ ]:
# import tensorflow as tf
# converter = tf.lite.TFLiteConverter.from_saved_model('/content/gdrive/MyDrive/Colab Notebooks/export-tflite/saved_model')
# tflite_model = converter.convert()

# with open('/content/gdrive/MyDrive/Colab Notebooks/export-tflite/model.tflite', 'wb') as f:
#   f.write(tflite_model)

In [ ]:
# converter = tf.lite.TFLiteConverter.from_saved_model('/content/gdrive/MyDrive/Colab Notebooks/export-tflite/saved_model')
# converter.optimizations = [tf.lite.Optimize.DEFAULT]
# model_quantization_1 = converter.convert()

# with open('/content/gdrive/MyDrive/Colab Notebooks/export-tflite/model_quantization_1.tflite', 'wb') as f:
#   f.write(model_quantization_1)

In [4]:
import numpy as np

def representative_data_gen():
  path = '/content/gdrive/My Drive/Colab Notebooks/deeppicar/images/lego-stop-signs/train'
  dataset_list = tf.data.Dataset.list_files(path + '/*.jpg')  
  for i in range(17):
    image = next(iter(dataset_list))
    image = tf.io.read_file(image)
    image = tf.io.decode_jpeg(image, channels=3)
    image = tf.image.resize(image, [300, 300])
    image = tf.cast(image / 255., tf.float32)
    image = tf.expand_dims(image, 0)
    print(image)
    yield [image]

In [9]:
# Some combinations of this will produce an output, but likely nothing will compile with edgetpu-compiler, these
# outputs are also very small files (~2000 kilobytes)
import tensorflow as tf

converter = tf.lite.TFLiteConverter.from_saved_model('/content/gdrive/MyDrive/Colab Notebooks/fine_tuned_model/saved_model')
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.inference_input_type = tf.uint8
converter.inference_output_type = tf.uint8
# converter.allow_custom_ops = True
# converter.experimental_new_converter = False
converter.representative_dataset = tf.lite.RepresentativeDataset(representative_data_gen)
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
#,tf.lite.OpsSet.TFLITE_BUILTINS
converter.target_spec.supported_types = [tf.int8]
quantized_model_tflite = converter.convert()

with open('/content/gdrive/MyDrive/Colab Notebooks/export-tflite/model-quantized-for-edge-tpu.tflite', 'wb') as f:
  f.write(quantized_model_tflite)

ConverterError: ignored

So I got the above error. So I try to install tf-nightly

In [21]:
!pip install tf-nightly

In [3]:
# Some combinations of this will produce an output, but likely nothing will compile with edgetpu-compiler, these
# outputs are also very small files (~2000 kilobytes)
import tensorflow as tf

converter = tf.lite.TFLiteConverter.from_saved_model('/content/gdrive/MyDrive/Colab Notebooks/fine_tuned_model/saved_model')
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.inference_input_type = tf.uint8
converter.inference_output_type = tf.uint8
# converter.allow_custom_ops = True
# converter.experimental_new_converter = False
converter.representative_dataset = tf.lite.RepresentativeDataset(representative_data_gen)
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.target_spec.supported_types = [tf.int8]
quantized_model_tflite = converter.convert()

with open('/content/gdrive/MyDrive/Colab Notebooks/export-tflite/model-quantized-for-edge-tpu.tflite', 'wb') as f:
  f.write(quantized_model_tflite)

ValueError: ignored

So this forum is the closed thing to what I'm doing:
https://github.com/tensorflow/tensorflow/issues/42426

In [16]:
import numpy as np
# def what():
def representative_data_gen():
  path = '/content/gdrive/My Drive/Colab Notebooks/deeppicar/images/lego-stop-signs/train'
  dataset_list = tf.data.Dataset.list_files(path + '/*.jpg')  
  for i in range(10):
    image = next(iter(dataset_list))
    image = tf.io.read_file(image)
    image = tf.io.decode_jpeg(image, channels=3)
    image = tf.image.resize(image, [300, 300])
    # image = tf.image.convert_image_dtype(
    # image, tf.uint8, saturate=False, name=None
    # )
    image = tf.cast(image / 255., tf.float32)
    image = tf.expand_dims(image, 0)
    print(image)
    yield [image]
  # return representative_data_gen

  # img_data = tf.io.gfile.GFile(path, 'rb').read()
  # image = Image.open(BytesIO(img_data))
  # image = image.resize((300, 300))
  # (im_width, im_height) = image.size

  # return np.array(image.getdata()).reshape(
  #     (im_height, im_width, 3)).astype(np.uint8)


In [19]:
# dummy dataset
def representative_dataset():
    for _ in range(100):
      data = np.random.rand(1, 300, 300, 3)
      yield [data.astype(np.float32)]

# https://www.tensorflow.org/lite/performance/post_training_quantization
def representative_dataset():
  for data in tf.data.Dataset.from_tensor_slices((images)).batch(1).take(100):
    yield [data.astype(tf.float32)]

In [20]:
# Some combinations of this will produce an output, but likely nothing will compile with edgetpu-compiler, these
# outputs are also very small files (~2000 kilobytes)
import tensorflow as tf

converter = tf.lite.TFLiteConverter.from_saved_model('/content/gdrive/MyDrive/Colab Notebooks/fine_tuned_model/saved_model')
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.inference_input_type = tf.uint8
converter.inference_output_type = tf.uint8
# converter.allow_custom_ops = True
# converter.experimental_new_converter = False
converter.representative_dataset = representative_data_gen #what() #tf.lite.RepresentativeDataset(representative_data_gen)
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.target_spec.supported_types = [tf.int8]
quantized_model_tflite = converter.convert()

with open('/content/gdrive/MyDrive/Colab Notebooks/export-tflite/model-quantized-for-edge-tpu.tflite', 'wb') as f:
  f.write(quantized_model_tflite)

tf.Tensor(
[[[[0.69803923 0.6431373  0.5921569 ]
   [0.7019608  0.64705884 0.59607846]
   [0.7019608  0.64705884 0.6117647 ]
   ...
   [0.63882315 0.52509767 0.39960745]
   [0.65278435 0.53905886 0.41356862]
   [0.63529414 0.5411765  0.40784314]]

  [[0.69803923 0.6431373  0.5921569 ]
   [0.7019608  0.64705884 0.59607846]
   [0.7019608  0.64705884 0.6117647 ]
   ...
   [0.642258   0.5292626  0.40352902]
   [0.6374957  0.52858543 0.40149018]
   [0.6392157  0.54509807 0.4117647 ]]

  [[0.69803923 0.6431373  0.5921569 ]
   [0.69803923 0.6431373  0.5921569 ]
   [0.69686276 0.6419608  0.6066667 ]
   ...
   [0.61713755 0.51909834 0.3975297 ]
   [0.63254905 0.53450984 0.4129412 ]
   [0.63529414 0.5411765  0.40784314]]

  ...

  [[0.33521548 0.7158665  0.6764936 ]
   [0.2970192  0.67781144 0.63749737]
   [0.23737238 0.62952924 0.58796024]
   ...
   [0.16470589 0.64705884 0.39215687]
   [0.16196097 0.6364708  0.37372568]
   [0.1498832  0.6361577  0.3616479 ]]

  [[0.20800184 0.5943403  0.490226

ValueError: ignored

In [10]:
model_path = '/content/gdrive/MyDrive/Colab Notebooks/fine_tuned_model/saved_model'
loaded_model = tf.saved_model.load(model_path)
loaded_model



<tensorflow.python.saved_model.load.Loader._recreate_base_user_object.<locals>._UserObject at 0x7fa1193fa7b8>

In [11]:
print(list(loaded_model.signatures.keys()))

['serving_default']


In [13]:
infer = loaded_model.signatures["serving_default"]
print(infer.structured_outputs)

{'detection_multiclass_scores': TensorSpec(shape=(1, 100, 91), dtype=tf.float32, name='detection_multiclass_scores'), 'detection_classes': TensorSpec(shape=(1, 100), dtype=tf.float32, name='detection_classes'), 'num_detections': TensorSpec(shape=(1,), dtype=tf.float32, name='num_detections'), 'detection_boxes': TensorSpec(shape=(1, 100, 4), dtype=tf.float32, name='detection_boxes'), 'raw_detection_boxes': TensorSpec(shape=(1, 1917, 4), dtype=tf.float32, name='raw_detection_boxes'), 'detection_scores': TensorSpec(shape=(1, 100), dtype=tf.float32, name='detection_scores'), 'raw_detection_scores': TensorSpec(shape=(1, 1917, 91), dtype=tf.float32, name='raw_detection_scores'), 'detection_anchor_indices': TensorSpec(shape=(1, 100), dtype=tf.float32, name='detection_anchor_indices')}
